import test from "node:test";
import assert from "node:assert/strict";
import {
  PRESUPPOSITIONS,
  PRESUPPOSITIONAL_GLOSSARY,
  checkSemanticIntegrity,
  generateCompetingMechanisms,
  validateProvenanceChain,
  evaluateCausalBranches,
  buildResearchNode,
  type EmpiricalEvidence,
} from "./presuppositional-rag.ts";

test("Layer A: PRESUPPOSITIONS contains P1-P5 with immutable canonical definitions", () => {
  const keys = Object.keys(PRESUPPOSITIONS);
  assert.deepEqual(keys, ["P1", "P2", "P3", "P4", "P5"]);
  assert.match(PRESUPPOSITIONS.P1.canonicalDefinition, /Logos/);
  assert.match(PRESUPPOSITIONS.P2.canonicalDefinition, /telos/i);
  assert.match(PRESUPPOSITIONS.P3.canonicalDefinition, /Pattern recognition/);
  assert.match(PRESUPPOSITIONS.P4.canonicalDefinition, /directed, precise interaction/);
  assert.match(PRESUPPOSITIONS.P4.term, /Causal Interaction/);
  assert.match(PRESUPPOSITIONS.P5.canonicalDefinition, /Instrumental abstraction/);
});

test("Layer B: checkSemanticIntegrity intercepts term inversions on Logos and Telos", () => {
  const logosLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Logos")!;
  const telosLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Telos")!;
  const causalLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Causal Interaction")!;

  // Inversion on Logos
  const hitLogos = checkSemanticIntegrity(logosLock, "We treat Logos as arbitrary noise generated by social construct.");
  assert.equal(hitLogos.action, "redirect");
  assert.equal(hitLogos.deflection, "obtuse");
  assert.match(hitLogos.reroot, /Inversion: Logos/);

  // Inversion on Telos
  const hitTelos = checkSemanticIntegrity(telosLock, "Hierarchies develop through random drift without any real telos.");
  assert.equal(hitTelos.action, "redirect");
  assert.equal(hitTelos.deflection, "obtuse");

  // Inversion on Causal Interaction
  const hitCausal = checkSemanticIntegrity(causalLock, "Causal interaction is just passive observation and pure correlation.");
  assert.equal(hitCausal.action, "redirect");
  assert.equal(hitCausal.deflection, "obtuse");

  // Legitimate usage holds
  const holdHit = checkSemanticIntegrity(logosLock, "Logos provides the antecedent ordering principle.");
  assert.equal(holdHit.action, "hold");
  assert.equal(holdHit.deflection, "none");
});

test("Generative Lattice: expands exactly 7 non-dialectic causal mechanisms", () => {
  const branches = generateCompetingMechanisms("Observed power-law in network connectivity");
  assert.equal(branches.length, 7);
  const ids = branches.map((b) => b.id);
  assert.deepEqual(ids, ["M1", "M2", "M3", "M4", "M5", "M6", "M7"]);
});

test("Layer C: validateProvenanceChain enforces 4-stage primary provenance", () => {
  const validEvidence: EmpiricalEvidence = {
    sourceId: "DOC-001",
    provenance: {
      primaryDoc: "Blue Brain Project 2024",
      literalQuote: "Up to 11-dimensional geometric simplicial complexes",
      empiricalContext: "Cortical column simulation",
      derivedInterpretation: "High-dimensional cavities exist",
    },
    relevanceScore: 0.98,
  };
  assert.equal(validateProvenanceChain(validEvidence), true);

  const brokenEvidence: EmpiricalEvidence = {
    sourceId: "DOC-002",
    provenance: {
      primaryDoc: "",
      literalQuote: "Some secondary quote",
      empiricalContext: "Context",
      derivedInterpretation: "Interpretation",
    },
    relevanceScore: 0.5,
  };
  assert.equal(validateProvenanceChain(brokenEvidence), false);
});

test("Discriminating Lattice: prunes ungrounded branches and isolates anomalies", () => {
  const branches = generateCompetingMechanisms("11D clique density");
  const evidence: EmpiricalEvidence[] = [
    {
      sourceId: "DOC-001",
      provenance: {
        primaryDoc: "Blue Brain Project 2024",
        literalQuote: "forming up to 11-dimensional geometric simplicial complexes around empty cavities",
        empiricalContext: "Microcircuit stimulation",
        derivedInterpretation: "High-dimensional simplicial topology",
      },
      relevanceScore: 0.95,
    },
  ];

  const evalResult = evaluateCausalBranches(branches, evidence);
  assert.equal(evalResult.falsified.length, 2);
  assert.equal(evalResult.survivors.length, 5);
  assert.equal(evalResult.anomalies.length, 1);
  assert.match(evalResult.anomalies[0], /high-dimensional simplicial cavities/);
});

test("Research Node Schema: builds fully compliant TwinglassResearchNode", () => {
  const branches = generateCompetingMechanisms("Test");
  const evidence: EmpiricalEvidence[] = [
    {
      sourceId: "DOC-001",
      provenance: {
        primaryDoc: "Primary paper",
        literalQuote: "Literal text",
        empiricalContext: "Experimental setting",
        derivedInterpretation: "Causal takeaway",
      },
      relevanceScore: 0.9,
    },
  ];

  const node = buildResearchNode({
    nodeId: "NODE-TEST-001",
    propositionId: "P3",
    claim: "Neural connectivity reflects antecedent structural constraints.",
    mechanism: branches[5], // M6
    evidence,
    competingBranchIds: branches.map((b) => b.id),
    anomalies: ["Unexplained residue"],
  });

  assert.equal(node.node_id, "NODE-TEST-001");
  assert.equal(node.originating_proposition, "P3");
  assert.equal(node.epistemic_status, "PROVISIONAL_SYNTHESIS");
  assert.equal(node.causal_mechanism.id, "M6");
  assert.equal(node.retrieved_evidence.length, 1);
  assert.equal(node.semantic_locks.length, 5);
  assert.equal(node.competing_branch_ids.length, 7);
  assert.equal(node.unresolved_anomalies.length, 1);
});
