import test from "node:test";
import assert from "node:assert/strict";
import {
  PRESUPPOSITIONS,
  PRESUPPOSITIONAL_GLOSSARY,
  checkSemanticIntegrity,
  generateCompetingMechanisms,
  validateProvenanceChain,
  buildResearchNode,
  executeTetrahedralCritique,
  evaluateTriStateExitGate,
  type EmpiricalEvidence,
} from "./presuppositional-rag.ts";

test("Layer A: PRESUPPOSITIONS contains P1-P5 with immutable canonical definitions", () => {
  const keys = Object.keys(PRESUPPOSITIONS);
  assert.deepEqual(keys, ["P1", "P2", "P3", "P4", "P5"]);
  assert.match(PRESUPPOSITIONS.P1.canonicalDefinition, /Logos/);
  assert.match(PRESUPPOSITIONS.P2.canonicalDefinition, /telos/i);
  assert.match(PRESUPPOSITIONS.P3.canonicalDefinition, /Pattern recognition/);
  assert.match(PRESUPPOSITIONS.P4.canonicalDefinition, /directed, precise interaction/);
  assert.match(PRESUPPOSITIONS.P4.term, /Causal Interaction/);
  assert.match(PRESUPPOSITIONS.P5.canonicalDefinition, /Instrumental abstraction/);
});

test("Layer B: checkSemanticIntegrity intercepts term inversions on Logos and Telos", () => {
  const logosLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Logos")!;
  const telosLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Telos")!;
  const causalLock = PRESUPPOSITIONAL_GLOSSARY.find((g) => g.term === "Causal Interaction")!;

  // Inversion on Logos
  const hitLogos = checkSemanticIntegrity(logosLock, "We treat Logos as arbitrary noise generated by social construct.");
  assert.equal(hitLogos.action, "redirect");
  assert.equal(hitLogos.deflection, "obtuse");
  assert.match(hitLogos.reroot, /Inversion: Logos/);

  // Inversion on Telos
  const hitTelos = checkSemanticIntegrity(telosLock, "Hierarchies develop through random drift without any real telos.");
  assert.equal(hitTelos.action, "redirect");
  assert.equal(hitTelos.deflection, "obtuse");

  // Inversion on Causal Interaction
  const hitCausal = checkSemanticIntegrity(causalLock, "Causal interaction is just passive observation and pure correlation.");
  assert.equal(hitCausal.action, "redirect");
  assert.equal(hitCausal.deflection, "obtuse");

  // Legitimate usage holds
  const holdHit = checkSemanticIntegrity(logosLock, "Logos provides the antecedent ordering principle.");
  assert.equal(holdHit.action, "hold");
  assert.equal(holdHit.deflection, "none");
});

test("Generative Lattice: expands exactly 7 non-dialectic causal mechanisms", () => {
  const branches = generateCompetingMechanisms("Observed power-law in network connectivity");
  assert.equal(branches.length, 7);
  const ids = branches.map((b) => b.id);
  assert.deepEqual(ids, ["M1", "M2", "M3", "M4", "M5", "M6", "M7"]);
});

test("Layer C: validateProvenanceChain enforces 4-stage primary provenance and exact span binding", () => {
  const sourceText = "Neuron groups assemble into all-to-all connected cliques forming up to 11-dimensional geometric simplicial complexes around dynamic empty cavities.";
  
  const validEvidence: EmpiricalEvidence = {
    sourceId: "DOC-001",
    provenance: {
      primaryDoc: "Markram, Reimann et al. 2017",
      literalQuote: "forming up to 11-dimensional geometric simplicial complexes around dynamic empty cavities",
      empiricalContext: "Cortical column simulation",
      derivedInterpretation: "High-dimensional cavities exist in reconstructed microcircuits",
    },
    relevanceScore: 0.98,
  };
  // Valid without source text
  assert.equal(validateProvenanceChain(validEvidence), true);
  // Valid with matching source text (sets exactSpanMatch: true)
  assert.equal(validateProvenanceChain(validEvidence, sourceText), true);
  assert.equal(validEvidence.provenance.exactSpanMatch, true);

  // Fails with mismatched source text
  const fabricatedQuoteEvidence: EmpiricalEvidence = {
    sourceId: "DOC-001",
    provenance: {
      primaryDoc: "Markram, Reimann et al. 2017",
      literalQuote: "Neurons communicate via non-physical telepathic entanglement",
      empiricalContext: "Cortical column simulation",
      derivedInterpretation: "Telepathic networks",
    },
    relevanceScore: 0.98,
  };
  assert.equal(validateProvenanceChain(fabricatedQuoteEvidence, sourceText), false);
  assert.equal(fabricatedQuoteEvidence.provenance.exactSpanMatch, false);

  // Fails with tautological self-paraphrase
  const tautologicalEvidence: EmpiricalEvidence = {
    sourceId: "DOC-003",
    provenance: {
      primaryDoc: "Paper",
      literalQuote: "Exact same text",
      empiricalContext: "Context",
      derivedInterpretation: "Exact same text",
    },
    relevanceScore: 0.5,
  };
  assert.equal(validateProvenanceChain(tautologicalEvidence), false);

  const brokenEvidence: EmpiricalEvidence = {
    sourceId: "DOC-002",
    provenance: {
      primaryDoc: "",
      literalQuote: "Some quote",
      empiricalContext: "Context",
      derivedInterpretation: "Interpretation",
    },
    relevanceScore: 0.5,
  };
  assert.equal(validateProvenanceChain(brokenEvidence), false);
});

test("Research Node Schema: builds fully compliant TwinglassResearchNode", () => {
  const branches = generateCompetingMechanisms("Test");
  const evidence: EmpiricalEvidence[] = [
    {
      sourceId: "DOC-001",
      provenance: {
        primaryDoc: "Primary paper",
        literalQuote: "Literal text",
        empiricalContext: "Experimental setting",
        derivedInterpretation: "Causal takeaway",
      },
      relevanceScore: 0.9,
    },
  ];

  const node = buildResearchNode({
    nodeId: "NODE-TEST-001",
    propositionId: "P3",
    claim: "Neural connectivity reflects antecedent structural constraints.",
    mechanism: branches[5], // M6
    evidence,
    competingBranchIds: branches.map((b) => b.id),
    anomalies: ["Unexplained residue"],
  });

  assert.equal(node.node_id, "NODE-TEST-001");
  assert.equal(node.originating_proposition, "P3");
  assert.equal(node.epistemic_status, "PROVISIONAL_SYNTHESIS");
  assert.equal(node.causal_mechanism.id, "M6");
  assert.equal(node.retrieved_evidence.length, 1);
  assert.equal(node.semantic_locks.length, 5);
  assert.equal(node.competing_branch_ids.length, 7);
  assert.equal(node.unresolved_anomalies.length, 1);
});

test("3D Tetrahedral Critique: executes 4 tracks and generates cross-track relational discriminations", () => {
  const critique = executeTetrahedralCritique({
    bareData: "All-to-all connectivity detected in 11-neuron cluster without transmission loss.",
    literatureFrame: "Author asserts this proves non-classical quantum coherence in cortical columns.",
    pretrainingBiasCheck: "Parametric prior defaults to synaptic neurotransmission. Disentangled prior from prompt.",
    phaseSpaceAnalysis: "Phase space reveals that classical cable theory with ephaptic coupling accounts for synchrony beyond flat networks.",
  });

  assert.match(critique.structural_critique_report, /Bare Data/);
  assert.match(critique.structural_critique_report, /Literature Frame/);
  assert.match(critique.structural_critique_report, /Bias Audit/);
  assert.match(critique.structural_critique_report, /Geometric Phase Space/);
  
  // Cross-track relational surfaces
  assert.equal(critique.relations.t1_t2_inferential_gap.load, "unwarranted_leap");
  assert.equal(critique.relations.t2_t3_sycophancy_audit.isEcho, false);
  assert.equal(critique.relations.t3_t4_causal_friction.deflected, true);
  assert.equal(critique.isSelfCritiquePassed, true);
});

test("Tri-State Exit Gate: routes to SLEEP_DOOR, CONSTRICTION_POINT, or CONTINUE_RESEARCH with active critique/anomaly participation", () => {
  const cleanCritique = executeTetrahedralCritique({
    bareData: "All-to-all connectivity in 11-neuron cluster.",
    literatureFrame: "High-dimensional simplicial topology.",
    pretrainingBiasCheck: "Disentangled prior from prompt.",
    phaseSpaceAnalysis: "Phase space reveals dynamic attractor beyond flat network.",
  });

  // Test 1: Needs neighbor variable -> SLEEP_DOOR
  const sleepGate = evaluateTriStateExitGate({
    critique: cleanCritique,
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: true,
    neighborName: "Simplicial_Cliques",
    isEndpointReached: false,
    isMutuallyExclusive: false,
  });
  assert.equal(sleepGate.decision, "SLEEP_DOOR");
  assert.equal(sleepGate.sleepPacket?.otherTrackEvidence, "Simplicial_Cliques");

  // Test 2: Endpoint reached + clean critique + no anomalies -> CONSTRICTION_POINT (debate)
  const debateGate = evaluateTriStateExitGate({
    critique: cleanCritique,
    integrity: { semanticIntegrityClear: true, dataIntegrityClear: true },
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: false,
    isEndpointReached: true,
    isMutuallyExclusive: true,
  });
  assert.equal(debateGate.decision, "CONSTRICTION_POINT");
  assert.equal(debateGate.constrictionMode, "debate");

  // Test 3: Complementary evidence can synthesize without manufacturing a debate or tetrahedron
  const synthGate = evaluateTriStateExitGate({
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: false,
    isEndpointReached: true,
    isMutuallyExclusive: false,
  });
  assert.equal(synthGate.decision, "CONSTRICTION_POINT");
  assert.equal(synthGate.constrictionMode, "synthesis");

  // Test 4: Endpoint claimed BUT unresolved anomalies exist -> BLOCKS constriction, routes to CONTINUE_RESEARCH
  const anomalyBlockedGate = evaluateTriStateExitGate({
    critique: cleanCritique,
    integrity: { semanticIntegrityClear: true, dataIntegrityClear: true },
    hasUnresolvedAnomalies: true,
    needsNeighborVariable: false,
    isEndpointReached: true,
    isMutuallyExclusive: false,
  });
  assert.equal(anomalyBlockedGate.decision, "CONTINUE_RESEARCH");
  assert.match(anomalyBlockedGate.reason, /Unresolved evidence remains/);

  // Test 5: Debate identified BUT pre-debate critique failed -> BLOCKS debate
  const failingCritique = executeTetrahedralCritique({
    bareData: "Data",
    literatureFrame: "Frame",
    pretrainingBiasCheck: "Bias",
    phaseSpaceAnalysis: "Trajectory without deflection",
  });
  assert.equal(failingCritique.isSelfCritiquePassed, false);
  const critiqueBlockedGate = evaluateTriStateExitGate({
    critique: failingCritique,
    integrity: { semanticIntegrityClear: true, dataIntegrityClear: true },
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: false,
    isEndpointReached: true,
    isMutuallyExclusive: true,
  });
  assert.equal(critiqueBlockedGate.decision, "CONTINUE_RESEARCH");
  assert.match(critiqueBlockedGate.reason, /Pre-debate tetrahedral self-critique/);
});



test("Ordinary research gathering does not require tetrahedral critique", () => {
  const gate = evaluateTriStateExitGate({
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: false,
    isEndpointReached: false,
    isMutuallyExclusive: false,
  });
  assert.equal(gate.decision, "CONTINUE_RESEARCH");
  assert.match(gate.reason, /Keep gathering research/);
});

test("A proposed debate requires both outside integrity auditors after self-critique", () => {
  const cleanCritique = executeTetrahedralCritique({
    bareData: "Observed connectivity data",
    literatureFrame: "Interpretive frame",
    pretrainingBiasCheck: "Disentangled prior from prompt",
    phaseSpaceAnalysis: "Phase space reveals an evidence-responsive attractor",
  });
  const noAudit = evaluateTriStateExitGate({
    critique: cleanCritique,
    hasUnresolvedAnomalies: false,
    needsNeighborVariable: false,
    isEndpointReached: true,
    isMutuallyExclusive: true,
  });
  assert.equal(noAudit.decision, "CONTINUE_RESEARCH");
  assert.match(noAudit.reason, /Pre-debate integrity clearance incomplete/);
});